apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-init
  labels:
    app: {{ template "yugaware.name" . }}
    chart: {{ template "yugaware.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Values.helm2Legacy | ternary "Tiller" (.Release.Service | quote) }}
data:
  init-prometheus.sh: |
    #!/bin/bash

    set -xe -o pipefail

    current_prom_directory="/prometheus"
    new_prom_directory="/prometheus/prometheus_data"
    exclude_list=(
      "./data"
      "./postgres_data_14"
      "./postgres_data"
      "./postgres_data_13"
      "./ybdb_data"
      "./swamper_rules"
      "./swamper_targets"
      "./releases"
      "./ybc_releases"
      "./prometheus_data"
    )
    if [[ -d "${new_prom_directory}" ]] && [[ -z "$(ls -A "${new_prom_directory}")" ]]; then
      cd "${current_prom_directory}";
      find . \( \
        -name "prometheus.yml" \
        $(printf -- '-o -path "%s" ' "${exclude_list[@]}") \
        \) -prune -o -type f -exec cp --parents -t /prometheus_data {} +
    fi
